1. Задан двухмерный массив ar1 размерности (10, 10), состоящий из случайных целых чисел в пределах от 0 до 15. Вычислить разность s_odd - s_even, где s_odd - сумма элементов, стоящих на позиции (x, y), где (x + y) является нечетным числом; s_even - сумма элементов, стоящих на позиции (x, y), где (x + y) является четным числом.
Решить задачу средствами numpy и/или pandas. Не использовать циклы и конструкции стандартного Python там, где можно использовать возможности данных библиотек


In [1]:
import numpy as np

In [2]:
ar1 = np.random.randint(0,15,size =(10,10))
ar1

array([[ 4, 12,  4,  5, 14,  1,  6, 13, 12,  9],
       [10,  4, 10,  3, 14, 13,  5, 12,  3,  0],
       [ 6,  5,  6,  2,  9,  0,  3,  8,  9, 14],
       [ 8,  3, 13,  1,  4,  3,  4,  6, 10, 10],
       [ 4,  5,  9, 10, 11,  3,  3,  9, 13, 14],
       [ 8,  4,  0,  8,  5, 14, 13,  5,  4,  9],
       [ 6,  6,  4,  2, 13,  2,  7, 10, 11,  4],
       [ 5, 14, 12,  7,  4,  3,  0,  9,  6, 13],
       [11, 11, 11,  0,  9,  3,  9,  9, 10,  2],
       [ 8,  4,  3,  2,  9,  1,  9,  2, 14,  8]])

In [ ]:
КАК СТОЯТ ЭЛЕМЕНТЫ

четн нечетн четн нечетн
нечетн четн нечетн четн 
четн нечетн четн нечетн 
нечетн четн нечетн четн

In [3]:
ar1[::2]

array([[ 4, 12,  4,  5, 14,  1,  6, 13, 12,  9],
       [ 6,  5,  6,  2,  9,  0,  3,  8,  9, 14],
       [ 4,  5,  9, 10, 11,  3,  3,  9, 13, 14],
       [ 6,  6,  4,  2, 13,  2,  7, 10, 11,  4],
       [11, 11, 11,  0,  9,  3,  9,  9, 10,  2]])

In [4]:
ar1[1::2]

array([[10,  4, 10,  3, 14, 13,  5, 12,  3,  0],
       [ 8,  3, 13,  1,  4,  3,  4,  6, 10, 10],
       [ 8,  4,  0,  8,  5, 14, 13,  5,  4,  9],
       [ 5, 14, 12,  7,  4,  3,  0,  9,  6, 13],
       [ 8,  4,  3,  2,  9,  1,  9,  2, 14,  8]])

In [38]:
s_even = np.sum((ar1[::2,::2], ar1[1::2,1::2]))
s_even

339

In [39]:
s_odd = np.sum((ar1[1::2,::2], ar1[::2,1::2]))
s_odd

323

In [34]:
print(s_odd-s_even)

-16


СВЕРЯЕМСЯ

In [19]:
s_odd = 0
s_even = 0
for i in range(ar1.shape[0]):
    for j in range(ar1.shape[1]):
        if (np.sum([i,j])%2==1):
            s_odd+=ar1[i][j]
        else:
            s_even+=ar1[i][j]
            
s_odd

323

In [20]:
s_even

339

In [21]:
s_odd-s_even

-16

In [7]:
import numpy as np
t = np.array([[8,4,15,6,9],
             [3,16,13,8,10],
             [0,9,18,17,5],
             [16,2,6,0,19],
             [18,13,9,17,8]])
np.resize(t.min(axis=1),(5,5)).transpose() + t.min(axis =0)

array([[ 4,  6, 10,  4,  9],
       [ 3,  5,  9,  3,  8],
       [ 0,  2,  6,  0,  5],
       [ 0,  2,  6,  0,  5],
       [ 8, 10, 14,  8, 13]])

In [9]:
t.min(axis=0)

array([0, 2, 6, 0, 5])