# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [31]:
arr = np.random.uniform(0,20,size=(4,7))
arr
for i in range(len(arr)):
    for j in range(len(arr[i])):
        arr[i][j] = (arr[i][j] - np.min(arr))/(np.max(arr) - np.min(arr))
arr

array([[0.85920024, 0.21048132, 0.09436009, 0.78944887, 0.11155215,
        0.67098151, 0.42164806],
       [0.34112504, 0.87079618, 0.40817726, 0.44816923, 0.14478494,
        0.78897244, 0.60087748],
       [0.8400135 , 0.88465501, 0.39624289, 0.6733499 , 0.00430155,
        0.23807232, 0.51858299],
       [0.76129072, 0.59258657, 0.93052185, 0.42617733, 0.32040103,
        1.        , 1.        ]])

In [32]:
arr = np.random.uniform(0,20,size=(4,7)) # uniform задает вещественные числа
arr = (arr - np.min(arr))/(np.max(arr)-np.min(arr))
arr

array([[0.15645779, 0.54022265, 0.31048096, 1.        , 0.92897401,
        0.66492573, 0.93797404],
       [0.15554872, 0.60856035, 0.91845582, 0.78455054, 0.20004495,
        0.87008967, 0.        ],
       [0.28605291, 0.08458561, 0.34480448, 0.26011013, 0.50508509,
        0.86440273, 0.07500881],
       [0.70947643, 0.23216815, 0.25378945, 0.95203514, 0.47654846,
        0.56713973, 0.16781348]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
arr = np.random.randint(0,10,size=(8,11)) # randint - задаем целые числа 
print(arr)

arr_sum = (np.sum(arr, axis = 1))
print("Суммы в строках",  arr_sum)

arr_min = np.min(arr_sum)
arr_min_indx = arr_sum.argmin()

print("Минимальная сумма в строке", arr_min)
print("Индекс минимальной суммы в строке", arr_min_indx)

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

Всё, что ниже использует массив res из первых 5 записей - это для теста. Для сдачи нужно использовать массив result

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [77]:
import numpy as np
file_name = "minutes_n_ingredients.csv"
result = np.loadtxt(file_name, delimiter=',', skiprows=1, dtype='int32')
print(result[:5])
res = result[:10]

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [127244     60     16]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [3]:
min_1 = np.amin(res, axis=0)[1]
min_2 = np.amin(res, axis=0)[2]

max_1 = np.amax(res, axis=0)[1]
max_2 = np.amax(res, axis=0)[2]

mean_1 = np.mean(res, axis=0)[1]
mean_2 = np.mean(res, axis=0)[2]

median_1 = np.median(res, axis=0)[1]
median_2 = np.median(res, axis=0)[2]

print(median_1, median_2)

print(mean_1, mean_2)

print(min_1, min_2)
print(max_1, max_2)


60.0 14.0
43.0 11.8
10 6
60 16


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [4]:
a = np.quantile(result, q = 0.75, axis = 0)[1]
#axis = 0 - стобцы, axis = 1 - строки
print(a)

65.0


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [85]:
print("res = ", res)
answ = res[res[:, 1] == 60]
print("itog = ", answ)

answ[:, 1] = 1
print("\n result=", answ)

res =  [[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [127244     60     16]
 [157911     60     14]
 [152828     40      7]
 [ 33941     18      9]
 [446597     15      5]
 [366174      7      9]
 [ 74205     20      7]]
itog =  [[127244     60     16]
 [127244     60     16]
 [157911     60     14]]

 result= [[127244      1     16]
 [127244      1     16]
 [157911      1     14]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [6]:
arr = [[1, 1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0],
       [0, 1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0]]
#только вместо arr наш массив, это просто для теста
unique_rows = np.unique(res, axis=0)
print(unique_rows)
print(len(unique_rows))

[[ 23891     25      7]
 [ 94746     10      6]
 [127244     60     16]
 [157911     60     14]]
4


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [54]:
print(res)
a = res[:,2]
print(a)
unique_ingr = np.unique(a, axis=0)
print(unique_ingr)
print("Kolvo unikalnih = ", len(unique_ingr))

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [127244     60     16]
 [157911     60     14]]
[16  7  6 16 14]
[ 6  7 14 16]
Kolvo unikalnih =  4


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [7]:
print(res)
s = res[:, 2]
print("s = ", s)
print(res[np.where((s <= 10))])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [127244     60     16]
 [157911     60     14]]
s =  [16  7  6 16 14]
[[23891    25     7]
 [94746    10     6]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [8]:
s = res[:, 2]
s1 = res[:, 1]
print("s1 = ", s1)
max_avr = max(s / s1)
max_2_avr = np.max(s / s1)
print(max_2_avr, max_avr)
print(s / s1)

s1 =  [60 25 10 60 60]
0.6 0.6
[0.26666667 0.28       0.6        0.26666667 0.23333333]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [9]:
res1 = np.array(sorted(res, key=lambda x :x[1], reverse=True))
print(res1)
answer = res1[:3]
mean_answ = np.mean(answer, axis=0)[2]
print(mean_answ)

[[127244     60     16]
 [127244     60     16]
 [157911     60     14]
 [ 23891     25      7]
 [ 94746     10      6]]
15.333333333333334


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [10]:
rand_3 = np.random.permutation(res)[:3] #для нашего массива
print(rand_3)

[[ 94746     10      6]
 [157911     60     14]
 [127244     60     16]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [1]:
#это фактически кол-во рецептов, в которых колво ингредиентов меньше среднего, <mean_2 делить на общее число рецептов. А это длина массива res
s = res[:,2]
kolvo_rez = res[np.where(s < mean_2)]
print(len(kolvo_rez) / len(res) * 100, "%")

NameError: name 'res' is not defined

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [116]:
res_simple = np.insert(res, 3, 0, axis=1)#добавление столбца. 3 - наш столбец должен стать 3м, 0 - то, что мы добавляем 
print(res_simple)
ingr = res_simple[:, 2]
time_min = res_simple[:, 1]
print("time_min = ", time_min)
print("ingr = ", ingr)

mask = (ingr <= 10) & (time_min <= 20)
print(mask)
new_res_simpl = np.c_[res, mask] #какой то объект, который сцепляет столбцы
print(new_res_simpl)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 [127244     60     16      0]
 [157911     60     14      0]
 [152828     40      7      0]
 [ 33941     18      9      0]
 [446597     15      5      0]
 [366174      7      9      0]
 [ 74205     20      7      0]]
time_min =  [60 25 10 60 60 40 18 15  7 20]
ingr =  [16  7  6 16 14  7  9  5  9  7]
[False False  True False False False  True  True  True  True]
[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      1]
 [127244     60     16      0]
 [157911     60     14      0]
 [152828     40      7      0]
 [ 33941     18      9      1]
 [446597     15      5      1]
 [366174      7      9      1]
 [ 74205     20      7      1]]


13. Выведите процент "простых" рецептов в датасете

In [120]:
kolvo_simple = np.sum(new_res_simpl, axis=0)
# print(kolvo_simple)
print(kolvo_simple[3] / len(res) * 100)

50.0


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [125]:
time_min = res[:, 1]
short_rec = res[np.where((time_min <= 10))]
standart_rec = res[np.where((time_min > 10) & (time_min < 20))]
long_rec = res[np.where((time_min >= 20))]
print("shape short", short_rec.shape)
print("short = ", short_rec)
print("shape standart", standart_rec.shape)
print("standart = ", standart_rec)
print("shape long", long_rec.shape)
print("long = ", long_rec)


min_shape_1 = min(short_rec.shape[0], standart_rec.shape[0], long_rec.shape[0])

my_arr = np.stack((short_rec[:min_shape_1], standart_rec[:min_shape_1],long_rec[:min_shape_1]))
print("itog = ", my_arr)


shape short (2, 3)
short =  [[ 94746     10      6]
 [366174      7      9]]
shape standart (2, 3)
standart =  [[ 33941     18      9]
 [446597     15      5]]
shape long (6, 3)
long =  [[127244     60     16]
 [ 23891     25      7]
 [127244     60     16]
 [157911     60     14]
 [152828     40      7]
 [ 74205     20      7]]
itog =  [[[ 94746     10      6]
  [366174      7      9]]

 [[ 33941     18      9]
  [446597     15      5]]

 [[127244     60     16]
  [ 23891     25      7]]]


In [ ]:
lst = [1,2,5,10,47,92]
lst


In [ ]:
[i**2 for i in lst]


In [ ]:
import numpy as np

In [ ]:
arr = np.array(lst)
arr

In [ ]:
arr + arr

In [ ]:
lst + lst

In [ ]:
arr[1:5:2]

In [ ]:
mask = arr % 5 == 0
mask

In [ ]:
arr[mask]

In [ ]:
b = np.array([0,1,2,2,0,1])
arr[b]

In [ ]:
arr = np.arange(5)

In [ ]:
arr

In [ ]:
arr = np.arange(20).reshape(5,4)
arr

In [ ]:
arr[:2, 1:3]

In [ ]:
arr = [[23,54,6], [45,65], [67,87,8,98,7]]


In [ ]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr[2:10:2]
# arr[START:STOP:STEP]
# По умолчанию(!) START=0, STOP=len(arr), STEP=1
arr[::-1]
#взять от 2го элемента до 10го каждый второй элемент